name: flutter_firebase_ddd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  flutter_bloc: ^7.0.0
  freezed_annotation: ^0.14.1
  google_sign_in: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^0.14.1+1

flutter:
  uses-material-design: true
